/// Represents the sender type of a chat message.
enum ChatSender {
  user,   // The message was sent by the user
  tutor,  // The message was sent by LumiTutor
  system  // The message was generated by the system (optional)
}
