// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtWdXjF9ZrXb6aIiHNWXeSoktdU3mnQPs',
    appId: '1:229129204738:web:6e38581c8f9d33e8bc231b',
    messagingSenderId: '229129204738',
    projectId: 'lumi-7f941',
    authDomain: 'lumi-7f941.firebaseapp.com',
    storageBucket: 'lumi-7f941.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeMJ5z_v1sRxD_phkOOkNykuJFvM2Kegs',
    appId: '1:229129204738:android:9d646650c3b2a1c6bc231b',
    messagingSenderId: '229129204738',
    projectId: 'lumi-7f941',
    storageBucket: 'lumi-7f941.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApd2zqbOQeeHY9B8tPino1VkFxokKhk_0',
    appId: '1:229129204738:ios:7d486e7269b7f031bc231b',
    messagingSenderId: '229129204738',
    projectId: 'lumi-7f941',
    storageBucket: 'lumi-7f941.firebasestorage.app',
    iosClientId: '229129204738-s1inn17kt935vr7kvv9tkbov8pr6tphi.apps.googleusercontent.com',
    iosBundleId: 'com.herlop.lumilearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApd2zqbOQeeHY9B8tPino1VkFxokKhk_0',
    appId: '1:229129204738:ios:7d486e7269b7f031bc231b',
    messagingSenderId: '229129204738',
    projectId: 'lumi-7f941',
    storageBucket: 'lumi-7f941.firebasestorage.app',
    iosClientId: '229129204738-s1inn17kt935vr7kvv9tkbov8pr6tphi.apps.googleusercontent.com',
    iosBundleId: 'com.herlop.lumilearn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtWdXjF9ZrXb6aIiHNWXeSoktdU3mnQPs',
    appId: '1:229129204738:web:ff6095f7e6027304bc231b',
    messagingSenderId: '229129204738',
    projectId: 'lumi-7f941',
    authDomain: 'lumi-7f941.firebaseapp.com',
    storageBucket: 'lumi-7f941.firebasestorage.app',
  );

}